### ISSUE TITLE
[ui5-menu-item]: Incorrect spelling of `ui5-menu-rp-sub-menu` class

### ISSUE THREAD

**Issue by dimovpetar** [SAP/ui5-webcomponents#11043]
In `MenuItemTemplate.tsx`, `ui5-menu-rp-sub-menu` class is written with leading dot, which is incorrect. As a results, some CSS selectors depending on this class are ineffective.

https://github.com/SAP/ui5-webcomponents/blob/078d44c92d32c10756ddf848907386ccecd3d354/packages/main/src/MenuItemTemplate.tsx#L81

After the fix, test if the following styles, located in `MenuItem.css`, are needed:
```css
.ui5-menu-rp.ui5-menu-rp-sub-menu {
	margin-top: 0.25rem;
	margin-inline: var(--_ui5_menu_submenu_margin_offset);
}

.ui5-menu-rp.ui5-menu-rp-sub-menu[actual-placement="Start"] {
	margin-top: 0.25rem;
	margin-inline: var(--_ui5_menu_submenu_placement_type_left_margin_offset);
}
```
