### ISSUE TITLE
[theming]: valid css class names are excluded

### ISSUE THREAD

**Issue by slin-sap** [SAP/ui5-webcomponents#11413]
### Bug Description

I created a custom sapui5 webcomponent project. I managed to integrate tailwindcss with the project. Most tailwind atomic classes can be rendered without problem. However, I noticed that some valid css classes generated by tailwindcss cannot be included in the runtime. These class name having backslash escape character in the css classname.

Version 2.9.0
Template Engine: JSX

### Expected Behaviour

CSS class names with backslash will be included at runtime. 

E.g.

```css
  .w-\[100px\] {
    width: 100px;
  }
```

### Steps to Reproduce

1. Add the following css class in any css file in src/themes. 

```css
  .flex {
    display: flex;
  }
  .flex-col {
    flex-direction: column;
  }
  .w-\[100px\] {
    width: 100px;
  }
  .grid {
    display: grid;
  }
  .grid-cols-2 {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
  .md\:grid-cols-3 {
    @media (width >= 48rem) {
      grid-template-columns: repeat(3, minmax(0, 1fr));
    }
  }
  .lg\:grid-cols-4 {
    @media (width >= 64rem) {
      grid-template-columns: repeat(4, minmax(0, 1fr));
    }
  }
  .xl\:grid-cols-5 {
    @media (width >= 80rem) {
      grid-template-columns: repeat(5, minmax(0, 1fr));
    }
  }
```

2. Add these css classes to a html tag in a webcomponent template. You can see that the css classes without backslashes are included in the webcomponent's css at runtime. But those with backslahes in the css class names are not working.

E.g.

```html
<div class="flex flex-col w-[100px] grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">
```

### Priority

None

### UI5 Web Components Version

2.9.0

### Browser

Chrome

### Declaration

- [x] I’m not disclosing any internal or sensitive information.
