### ISSUE TITLE
How to change width of ui5-select?

### ISSUE THREAD

**Issue by pta-nmu** [SAP/ui5-webcomponents#2423]
Hi,

Could you please post how to change the width of a <ui5-select> control in Angular (in the html template)?
It's not documented anywhere. 
Using <ui5-select id=..... style="width: 50%">  has no effect.

Thanks for your help

**Comment by ilhan007** [comment]
Hello @pta-nmu 

Does not applying standard CSS work?
```css
ui5-select {
width: 50px;
min-width: 50px;
}
```
