### ISSUE TITLE
TabContainer: implement responsive paddings

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents#2539]
**Is your feature request related to a problem? Please describe.**
Support different paddings in the TabContainer, depending on the component size (not screen size).

 
<img width="541" alt="Screenshot 2020-12-02 at 10 24 48 AM" src="https://user-images.githubusercontent.com/15702139/100859291-b9fcf180-3497-11eb-9ed1-9851a1ab2300.png">

**Left and right margins of the tabstrip (the tabs area) and the content area (below the tabs) should follow the global layout paddings:**

S: 1rem; (results in 16px); M: 2rem; L: 2rem; XL: 3rem; XXL: 3rem;
Size S   | <= 599px
Size M  | >=600px and <= 1023px
Size L   | >= 1024px and <= 1439px
Size XL | >= 1440px

**Describe the solution you'd like**

A private property (could be "size" or similar) that tracks the component size + CSS that is applied accordingly.
The property can be updated in the existing resize handler  "_handleHeaderResize".

```css
:host([size="M"])  {
	padding: 0 2rem;
}
:host([size="L"]) {
	padding: 0 2rem;
}
:host([size="XL"])  {
	padding: 3rem;
}
```

****Note:** The tabstrip area may require some DOM/CSS refactoring - it is not just changing few paddings.**
