### ISSUE TITLE
TabContainer style customization for content padding is missing

### ISSUE THREAD

**Issue by schamane** [SAP/ui5-webcomponents#2791]
Versions:

 "@ui5/webcomponents": "^1.0.0-rc.11",
 "@ui5/webcomponents-base": "^0.28.0", 
"@ui5/webcomponents-theme-base": "^1.0.0-rc.11",

There is no way to customize padding on Content for TabContainer content.

![image](https://user-images.githubusercontent.com/132251/107046701-375e1e80-67c7-11eb-946b-66b950d05de6.png)

Check this file:
https://github.com/SAP/ui5-webcomponents/blob/master/packages/main/src/themes/TabContainer.css

```css
.ui5-tc__content {
	position: relative;
	display: flex;
	height: calc(100% - var(--_ui5_tc_header_height)); /* the header height (tabs with icons and text) */
	padding: 1rem;
	background-color: var(--sapGroup_ContentBackground);
	border-bottom: var(--_ui5_tc_content_border_bottom);
	box-sizing: border-box;
}
```

Expected at least one of this solutions:
padding should be configurable over variable:

```css
padding: var(--_ui5_tc_content_padding);
```

or please support ::part css selectors for shadow dom
or provide other way to customize padding

**Comment by unazko** [comment]
Hello colleagues,

Could you please have a look at the proposed component enhancement.
There is a need to customize the TabContainer component padding as @schamane described in details.

Best Regards,
Boyan

**Comment by ilhan007** [comment]
Hello @schamane if you change the the padding of the content, the content and the tabstrip (above the content) won't be aligned. Currently there is change, prepared by @TeodorTaushanov  that aligns the content and the tabstrip and also make paddings responsive - based on current media.

PR: https://github.com/SAP/ui5-webcomponents/pull/2775

```css
:host([media-range="XL"]) .ui5-tc__content {
   padding: 1rem 3rem;
}
:host([media-range="XL"]) .ui5-tc__header {
   padding: 0 2rem;
}
```

So, if you set custom padding to the  "ui5-tc__content" element, you will break the responsive paddings and the alignment between the content and the tabstrip.
