### ISSUE TITLE
Custom Themes via Theme Designer is unstable/broken

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents#4346]
### **Bug Description**
When using the Theme Designer `css_variables.css` **and** the `custom.css` file (we need that for some specific overrides), the UI5 Web Components will not inject any theme.

### **Expected Behavior**
My custom theme should load (like in 1.0.0-rc.15).

**Additional Info**
If you swap
```html
    <link rel="stylesheet" href="css_variables.css" />
    <link rel="stylesheet" href="custom.css" />
```

to 

```html
    <link rel="stylesheet" href="custom.css" />
    <link rel="stylesheet" href="css_variables.css" />
```

the theme is loaded again, but this approach might invalidate some css variables that have been defined in `custom.css`.

### **Steps to Reproduce**
1. Open https://codesandbox.io/s/mutable-framework-ytjbv?file=/public/index.html:231-334
2. See the error

### **Isolated Example**
https://codesandbox.io/s/mutable-framework-ytjbv?file=/public/index.html:231-334

### **Context**
- UI5 Web Components version: 1.0.1
- OS/Platform: macOS
- Browser: Chrome 95.0.4638.69 (Official Build) (x86_64)
- Affected component: @ui5/webcomponents-base, most probably: https://github.com/SAP/ui5-webcomponents/blob/ce0dcd2ed2e078fb99af82f22acbda88cefd3fc1/packages/base/src/theming/getThemeDesignerTheme.js#L44-L47

### **Log Output / Stack Trace / Screenshots**
![image](https://user-images.githubusercontent.com/8775211/142004696-61d93d5d-3f9b-4b04-93a9-0947b01748cd.png)

### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [x] Very High

### **Stakeholder Info** (if applicable)

- Organization: UI5 Web Components for React / SAP Customer Experience
- Bussiness impact: Unable to upgrade the to the ^1.0.0 versions because this breaks our custom theming.

**Comment by IlianaB** [comment]
Hello @SAP/ui5-webcomponents-team I am forwarding this issue to you, because it seems with the new UI5 Web Components 1.0.1 version custom themes cannot be loaded, the same way like in 1.0.0-rc.15.

**Comment by vladitasev** [comment]
Hi @MarcusNotheis 

The problem is that both of these files contain a custom theme definition (metadata from Theme Designer). The one from `custom.css` seems to be:

![image](https://user-images.githubusercontent.com/15844574/142824548-5d0fd11d-6463-4a3a-95a3-969143cf2472.png)

which has invalid path in terms of theme recognition and the theme name cannot be properly extracted from the `Path` field. Probably in `r.c.-15` it failed silently. I'll push a fix to prevent the JS error from happening.

I'll keep you updated.

Regards,
Vladi

**Comment by vladitasev** [comment]
Hi again @MarcusNotheis 

There is a proposed fix, just to double-check that this is the expectation: The custom theme will be loaded from `css_variables.css` only, regardless of order. `custom.css` needs to be second in order to override some CSS Variables.

In the meantime, to overcome this error, you can delete the malformed metadata object from `custom.css`, namely this:

```css
.sapThemeMetaData-UI5-sap-ui-core {
  background-image: url('data:text/plain;utf-8,{"Path": "UI5.sap/ui/core.custom_quartzlight.custom", "PathPattern": "/%frameworkId%/%libId%/themes/%themeId%/%fileId%.css", "Extends": ["sap_fiori_3","base"], "Engine": {"Name": "theming-engine", "Version": "1.66.0"}, "Version": { "Build": "1.96.0.20211116152438", "Source": "1.96.0"}}');
}
```

This is the part that breaks the code.

Compare to the one from `css_variables.css`:

```css
.sapThemeMetaData-Base-baseLib{background-image: url('data:text/plain;utf-8,{"Path": "Base.baseLib.custom_quartzlight.css_variables", "PathPattern": "/%frameworkId%/%libId%/%themeId%/%fileId%.css", "Extends": ["sap_fiori_3","sap_base_fiori","baseTheme"], "Tags": ["Fiori_3","LightColorScheme"], "Engine": {"Name": "theming-engine", "Version": "1.66.0"}, "Version": { "Build": "11.1.34.20211116152438", "Source": "11.1.34"}}');}
```

Regards,
Vladi
