### ISSUE TITLE
Wrong padding in components

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents#4853]
### **Bug Description**
In addition to the two issues I've already opened (https://github.com/SAP/ui5-webcomponents/issues/4838, https://github.com/SAP/ui5-webcomponents/issues/4852) I found some more components with faulty padding. Since all of them have the same root cause, I didn't want to create an issue for each one of them. Hope that's ok with you.

- NotificationListItem: The padding of the content is wrong in the overflow popover
- NotificationListGroupItem: The padding of the content is wrong in the overflow popover
- ShellBar: The padding of the content is wrong in the overflow popover
- SideNavigation: In collapsed state, when clicking on an nav-item with sub-items, the popover has the wrong padding.
- TabContainer: In mobile mode, the footer has the wrong padding.

Issues I already raised:
- [DateTimePicker](https://github.com/SAP/ui5-webcomponents/issues/4852): The padding of the footer is wrong.
- [ViewSettingDialog](https://github.com/SAP/ui5-webcomponents/issues/4838): The padding of the header and footer is wrong.

If you prefer to have all the padding issues collected in this issue, you can close the two issues mentioned above and only keep this one open.

### **Context**
- UI5 Web Components version: 1.2.1

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by PetyaMarkovaBogdanova** [comment]
Hi @Lukas742 ,
for the TabContainer the padding seems fine to me, can you, please, attach a screenshot for just this case?
For all the others I will inform the relevant team to check.
Thank you!
Petya Markova.
(UI5 Dispatcher)

**Comment by Lukas742** [comment]
Hi @PetyaMarkovaBogdanova, 
sorry, my description was a bit vague. I meant the footer of the overflow popover in mobile mode.

<img width="429" alt="image" src="https://user-images.githubusercontent.com/9749730/156996518-e70dcf54-09ab-4c1b-9aeb-3901ec164a19.png">


<img width="477" alt="image" src="https://user-images.githubusercontent.com/9749730/156995807-c17d4db4-ef65-4f03-abb1-0a078e318d07.png">

```css
.ui5-responsive-popover-footer {
    display: flex;
    justify-content: flex-end;
    padding: 0.25rem;
    width: 100%;
}
```
<img width="463" alt="image" src="https://user-images.githubusercontent.com/9749730/156996246-ea5b092d-ef3c-4696-8ccd-dcbcd83efcac.png">

```css
:host([media-range="S"]) .ui5-popup-footer-root, :host([media-range="S"]) .ui5-popup-header-root {
    padding-left: var(--_ui5_popup_header_footer_padding_s);
    padding-right: var(--_ui5_popup_header_footer_padding_s);
}
```
