### ISSUE TITLE
List: Images rendered differently in Chrome/Safari

### ISSUE THREAD

**Issue by goodefroi** [SAP/ui5-webcomponents#4873]
### **Bug Description**
Image within list items are rendered as a circle on Safari whilst rendered as a square with round corners on Chrome.

### **Expected Behavior**
Both browsers render images in the same shape by default.

### **Steps to Reproduce**
Open the [documentation of the List component](https://sap.github.io/ui5-webcomponents/playground/components/List/) with both Chrome and Safari.

### **Context**
- UI5 Web Components version: 1.2.1
- OS/Platform: macOS 12.2.1
- Browser: Chrome 99/Safari 15.3
- Affected component: `ui5-list`

### **Screenshots**
Chrome 99:
<img width="386" alt="image" src="https://user-images.githubusercontent.com/27777253/157416721-c47cb16c-2cbf-43d9-a079-b8cf13fd9839.png">

Safari 15.3:
<img width="489" alt="image" src="https://user-images.githubusercontent.com/27777253/157416835-0712ee81-0a19-497b-a2a8-50e9ae28afff.png">

### **Priority**
- [x] Low
- [ ] Medium
- [ ] High
- [ ] Very High

**Comment by PetyaMarkovaBogdanova** [comment]
Hi colleagues,
ui5-avatar with shape "Square" is showed in circular shape in Safari.
Can you, please, check?

Kind regards,
Petya Markova.
(UI5 Dispatcher)

**Comment by ilhan007** [comment]
The second selector takes precedence on Safari


```css
/*  Avatar.css */
:host([shape=Square]),
:host([shape=Square]) ::slotted(*) {
  border-radius: .25rem;
}

::slotted(*) {
  border-radius: 50%;
}
```
