### ISSUE TITLE
[SF][Urgent][Firefox][1.2.1][Fix expected: within one week] Sap Horizon Theme does not work in Firefox browser

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents#4931]
Dear Colleagues,
I am from Shanghai Web Experience Team

**Bug Description**
Sap Horizon Theme does not work in Firefox browser

<img width="750" alt="Screen Shot 2022-03-21 at 3 38 28 PM" src="https://user-images.githubusercontent.com/78520316/159227326-c64427fb-a31c-48cb-83ef-d5da23c39259.png">

**Expected Behavior**
Sap Horizon Theme can work correctly in Firefox browser

I will put the demo link in slack channel due to our company's security policy

**Comment by ilhan007** [comment]
Hello @sfsf-xweb-sh 
we have prepared a [fix](https://github.com/SAP/ui5-webcomponents/pull/4934/) but we want to make sure it works properly on your side before merging, so if you can verify it would be best

Could you just add the following style somewhere in the head of your HTML page and re-check:
```css
@font-face {
    font-family: ‘72-Bold’;
    font-style: normal;
    src: local(‘72-Bold’),
    url(https://ui5.sap.com/sdk/resources/sap/ui/core/themes/sap_fiori_3/fonts/72-Bold.woff2?ui5-webcomponents) format(“woff2”),
    url(https://ui5.sap.com/sdk/resources/sap/ui/core/themes/sap_fiori_3/fonts/72-Bold.woff?ui5-webcomponents) format(“woff”);
}
```
