### ISSUE TITLE
ui5-table-column alignment

### ISSUE THREAD

**Issue by geokas7** [SAP/ui5-webcomponents#7091]
I created a ui5-table component with some ui5-table-column components. The automate alignment does not work very well . Is there a way to align better the text of the columns with the column name?

**Comment by ilhan007** [comment]
Hello @geokas7 
the columns and cells could be re-styled to achieve different alignment between the column name and the cell text, could you try the following and set the requited `text-align` to fit your design

```css
ui5-table-column::part(column) {
		text-align: left;
	}

	<ui5-table-cell style="text-align: left">
			<span style="color: #2b7c2b"><b>4.2</b>KG</span>
	</ui5-table-cell>
```
